# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
strategy:
  matrix:
    os: [ubuntu-latest, macos-latest]

jobs:
  build:
    runs-on: {{matrix.os}}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build CCR
      run: go build -v ./ccr.go
    - name: Build CNM
      run: go build -v ./cnm.go
  
#     - name: Test
#       run: go test -v ./...
